Fwmt 566 smoke test
ONSdigital/fwmt-job-service-v2 pull request #33
Opened 2018-10-23 14:50 UTC by ChrisHardmanONS

added endpoint to check rabbit connection and status

2018-10-24 10:27 UTC, sdiaz1000 requested changes
add private to the fields in RabbitCheckHealthController.java

2018-10-24 10:49 UTC, sdiaz1000 requested changes

2018-10-24 10:49 UTC, spdiaz1000 commented on src/main/java/uk/gov/ons/fwmt/job_service_v2/controller/RabbitCheckHealthController.java
> +    System.out.println(results);
remove sysount

2018-10-24 10:49 UTC, spdiaz1000 commented on src/main/java/uk/gov/ons/fwmt/job_service_v2/controller/RabbitCheckHealthController.java
> +  private CachingConnectionFactory getRMConnectionFactory() {
Autowire in the existing connection factory

2018-10-26 10:36 UTC, sdiaz1000 approved these changes

2018-10-26 10:36 UTC, merged